import {
  User,
  SecurityStaff,
  MasterUnit,
  MasterGedung,
  PatrolLocation,
  MasterVehicle,
  IncidentCategory,
  VisitPurpose,
  Visitor,
  DailyReport,
  PatrolLog,
  IncidentReport,
  LostAndFound,
  BarangTitipan,
  SchoolVehicleLog,
  SystemNotification,
  AuditLog,
} from '../types';

const today = new Date().toISOString().slice(0, 10);

export const initialLoginPolicy = {
  maxFailedAttempts: 3,
  lockoutDurationSeconds: 30,
  sessionTimeoutMinutes: 30,
  requirePinForSecurity: true,
  passwordMinLength: 6,
};

export const initialUsers: User[] = [
  {
    id: 'USR-01',
    username: 'admin',
    name: 'Ahmad Soleh (Admin)',
    role: 'Administrator',
    email: 'admin.security@lazuardi.sch.id',
    phone: '081298765432',
    unit: 'Direktorat',
    password: 'admin123',
    pin: '123456',
    status: 'Aktif',
    lastLogin: `${today} 07:30`,
  },
  {
    id: 'USR-02',
    username: 'supervisor',
    name: 'Sarmdi (Supervisor)',
    role: 'Supervisor Security',
    email: 'sarmdi.spv@lazuardi.sch.id',
    phone: '081388776655',
    unit: 'Security & Safety',
    password: 'super123',
    pin: '223344',
    status: 'Aktif',
    lastLogin: `${today} 08:00`,
  },
  {
    id: 'USR-03',
    username: 'ismail',
    name: 'Ismail (Petugas)',
    role: 'User',
    email: 'ismail.sec@lazuardi.sch.id',
    phone: '081512345678',
    unit: 'Security Pos Utama',
    password: 'user123',
    pin: '112233',
    status: 'Aktif',
    lastLogin: `${today} 06:45`,
  },
];

export const initialStaff: SecurityStaff[] = [
  { id: 'STF-01', nip: 'SEC-101', name: 'Ismail', phone: '081512345678', role: 'Komandan Regu', shiftDefault: 'Pagi', status: 'Aktif' },
  { id: 'STF-02', nip: 'SEC-102', name: 'Sarmdi', phone: '081388776655', role: 'Supervisor', shiftDefault: 'Pagi', status: 'Aktif' },
  { id: 'STF-03', nip: 'SEC-103', name: 'Ahmad Soleh', phone: '081298765432', role: 'Komandan Regu', shiftDefault: 'Siang', status: 'Aktif' },
  { id: 'STF-04', nip: 'SEC-104', name: 'Andreas Maulana', phone: '081477889900', role: 'Anggota', shiftDefault: 'Siang', status: 'Aktif' },
  { id: 'STF-05', nip: 'SEC-105', name: 'Moch Saepurrohman', phone: '081622334455', role: 'Anggota', shiftDefault: 'Siang', status: 'Aktif' },
  { id: 'STF-06', nip: 'SEC-106', name: 'Rizki Maulana', phone: '081733445566', role: 'Anggota', shiftDefault: 'Malam', status: 'Aktif' },
  { id: 'STF-07', nip: 'SEC-107', name: 'Coirul Fikri', phone: '081844556677', role: 'Anggota', shiftDefault: 'Malam', status: 'Aktif' },
  { id: 'STF-08', nip: 'SEC-108', name: 'Andyka Jessy Saputra', phone: '081955667788', role: 'Anggota', shiftDefault: 'Pagi', status: 'Aktif' },
  { id: 'STF-09', nip: 'SEC-109', name: 'Aditya Nugraha', phone: '082166778899', role: 'Anggota', shiftDefault: 'Malam', status: 'Aktif' },
  { id: 'STF-10', nip: 'SEC-110', name: 'Rizki Ramadhan', phone: '082277889900', role: 'Anggota', shiftDefault: 'Siang', status: 'Aktif' },
];

export const initialUnits: MasterUnit[] = [
  { id: 'UNT-01', code: 'INF', name: 'Informasi & Layanan Publik', headName: 'Siti Aminah', location: 'Lobby Utama' },
  { id: 'UNT-02', code: 'TK', name: 'Unit TK Lazuardi', headName: 'Nurul Huda', location: 'Gedung D' },
  { id: 'UNT-03', code: 'SD', name: 'Unit SD Lazuardi', headName: 'Budi Santoso', location: 'Gedung B' },
  { id: 'UNT-04', code: 'SMP', name: 'Unit SMP Lazuardi', headName: 'Dewi Rahmawati', location: 'Gedung C' },
  { id: 'UNT-05', code: 'SUP', name: 'Support & Sarpras', headName: 'Hendra Gunawan', location: 'Gedung Serba Guna' },
  { id: 'UNT-06', code: 'HRD', name: 'HRD & Personalia', headName: 'Rina Kartika', location: 'Gedung A Lt 2' },
  { id: 'UNT-07', code: 'LTB', name: 'Litbang & Kurikulum', headName: 'Dr. Faisal', location: 'Gedung A Lt 3' },
  { id: 'UNT-08', code: 'DIR', name: 'Direktorat Sekolah', headName: 'H. Ir. Ahmad', location: 'Gedung A Lt 3' },
];

export const initialGedung: MasterGedung[] = [
  { id: 'GDG-01', code: 'GD-A', name: 'Gedung Utama (Direktorat & HRD)', floors: 3, description: 'Kantor Administrasi & Manajemen' },
  { id: 'GDG-02', code: 'GD-B', name: 'Gedung SD Lazuardi', floors: 2, description: 'Ruang Kelas & Laboratorium SD' },
  { id: 'GDG-03', code: 'GD-C', name: 'Gedung SMP Lazuardi', floors: 3, description: 'Ruang Kelas & Lab Sains SMP' },
  { id: 'GDG-04', code: 'GD-D', name: 'Gedung TK & PAUD', floors: 1, description: 'Playground & Kelas TK' },
  { id: 'GDG-05', code: 'GD-GSG', name: 'Gedung Olahraga & Hall', floors: 2, description: 'Auditorium & Sarana Olahraga' },
];

export const initialPatrolLocations: PatrolLocation[] = [
  { id: 'LOC-01', code: 'QR-GRB-01', name: 'Gerbang Utama & Pos 1', gedungId: 'GDG-01', floor: 'Lantai 1', qrCode: 'LSMS-PATROL-GERBANG-UTAMA', description: 'Area akses keluar masuk utama kendaraan & pejalan kaki', targetTimesPerShift: 3 },
  { id: 'LOC-02', code: 'QR-LBY-01', name: 'Lobby Gedung Utama', gedungId: 'GDG-01', floor: 'Lantai 1', qrCode: 'LSMS-PATROL-LOBBY-A', description: 'Lobby penerima tamu & resepsionis', targetTimesPerShift: 2 },
  { id: 'LOC-03', code: 'QR-SD-01', name: 'Lorong Klas SD Lantai 2', gedungId: 'GDG-02', floor: 'Lantai 2', qrCode: 'LSMS-PATROL-SD-LT2', description: 'Area ruang kelas 4-6 SD', targetTimesPerShift: 2 },
  { id: 'LOC-04', code: 'QR-SMP-01', name: 'Laboratorium Komputer SMP', gedungId: 'GDG-03', floor: 'Lantai 2', qrCode: 'LSMS-PATROL-SMP-LAB', description: 'Ruang server lokal & Lab Komputer SMP', targetTimesPerShift: 2 },
  { id: 'LOC-05', code: 'QR-TK-01', name: 'Area Playground TK', gedungId: 'GDG-04', floor: 'Lantai 1', qrCode: 'LSMS-PATROL-TK-PLAYGROUND', description: 'Taman bermain & pagar perimeter TK', targetTimesPerShift: 3 },
  { id: 'LOC-06', code: 'QR-PRK-01', name: 'Area Parkir Mobil & Bus', gedungId: 'GDG-05', floor: 'Lantai 1', qrCode: 'LSMS-PATROL-PARKIR-UTAMA', description: 'Parkir armada kendaraan sekolah dan tamu', targetTimesPerShift: 3 },
  { id: 'LOC-07', code: 'QR-GSG-01', name: 'Auditorium & GSG', gedungId: 'GDG-05', floor: 'Lantai 2', qrCode: 'LSMS-PATROL-AUDITORIUM', description: 'Gedung Olahraga & Hall Acara', targetTimesPerShift: 2 },
];

export const initialVehicles: MasterVehicle[] = [
  { id: 'VHC-01', plateNumber: 'B 1029 LZ', name: 'Toyota HiAce Silver', type: 'Bus Sekolah', capacity: 15, status: 'Tersedia' },
  { id: 'VHC-02', plateNumber: 'B 1840 LZ', name: 'Daihatsu Gran Max Box', type: 'Mobil Operasional', capacity: 3, status: 'Digunakan' },
  { id: 'VHC-03', plateNumber: 'B 6789 LZ', name: 'Honda Beat Security', type: 'Motor Patroli', capacity: 2, status: 'Tersedia' },
];

export const initialIncidentCategories: IncidentCategory[] = [
  { id: 'CAT-01', code: 'INC-KCL', name: 'Kecelakaan', defaultPriority: 'Medium' },
  { id: 'CAT-02', code: 'INC-TBK', name: 'Tabrakan / Parkir', defaultPriority: 'Low' },
  { id: 'CAT-03', code: 'INC-TGK', name: 'Pertengkaran / Perkelahian', defaultPriority: 'High' },
  { id: 'CAT-04', code: 'INC-TIZ', name: 'Masuk Tanpa Izin', defaultPriority: 'Critical' },
  { id: 'CAT-05', code: 'INC-KHL', name: 'Kehilangan Barang', defaultPriority: 'Medium' },
  { id: 'CAT-06', code: 'INC-LNN', name: 'Lainnya', defaultPriority: 'Low' },
];

export const initialPurposes: VisitPurpose[] = [
  { id: 'PRP-01', name: 'Dinas / Kunjungan Instansi', description: 'Pemerintahan, Dinas Pendidikan, Kepolisian' },
  { id: 'PRP-02', name: 'Informasi Sekolah / Pendaftaran', description: 'Calon Orang Tua Siswa' },
  { id: 'PRP-03', name: 'Sales / Penawaran Produk', description: 'Vendor B2B' },
  { id: 'PRP-04', name: 'Vendor / Perbaikan Facilities', description: 'AC, CCTV, IT Infrastructure, Catering' },
  { id: 'PRP-05', name: 'Pertemuan Orang Tua & Guru', description: 'Konsultasi Belajar' },
];

export const initialVisitors: Visitor[] = [
  {
    id: 'VST-001',
    visitorNumber: 'VST-20260803-001',
    date: today,
    timeIn: '07:15',
    timeOut: undefined,
    name: 'Bambang Triyono',
    category: 'Vendor',
    phone: '081299887766',
    email: 'bambang.teknik@acservice.com',
    destinationUnit: 'Support',
    hostPerson: 'Hendra Gunawan (Sarpras)',
    purpose: 'Perbaikan Sistem Pendingin AC Gedung B SD',
    photoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    ktpPhotoUrl: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=150&auto=format&fit=crop&q=80',
    visitorCardNumber: 'CARD-012',
    receiverSecurity: 'Ismail',
    status: 'Masih di Sekolah',
    durationMinutes: 320, // > 4 hours (5h 20m) -> Overdue!
    isOverdueAlert: true,
  },
  {
    id: 'VST-002',
    visitorNumber: 'VST-20260803-002',
    date: today,
    timeIn: '08:30',
    timeOut: undefined,
    name: 'Drs. Supriyadi, M.Pd',
    category: 'Dinas',
    phone: '081311223344',
    email: 'supriyadi@disdik.depok.go.id',
    destinationUnit: 'Direktorat',
    hostPerson: 'H. Ir. Ahmad (Direktur)',
    purpose: 'Monitoring & Evaluasi Kesiapan Akreditasi School',
    photoUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    visitorCardNumber: 'CARD-001',
    receiverSecurity: 'Ahmad Soleh',
    status: 'Masih di Sekolah',
    durationMinutes: 200,
    isOverdueAlert: false,
  },
  {
    id: 'VST-003',
    visitorNumber: 'VST-20260803-003',
    date: today,
    timeIn: '09:00',
    timeOut: '10:45',
    name: 'Ratna Sari',
    category: 'Informasi Sekolah',
    phone: '081877665544',
    email: 'ratnasari@gmail.com',
    destinationUnit: 'Informasi',
    hostPerson: 'Siti Aminah',
    purpose: 'Konsultasi Pendaftaran Murid Baru Unit TK',
    photoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    visitorCardNumber: 'CARD-005',
    receiverSecurity: 'Andreas Maulana',
    checkoutSecurity: 'Ahmad Soleh',
    status: 'Sudah Keluar',
    durationMinutes: 105,
    isOverdueAlert: false,
  },
  {
    id: 'VST-004',
    visitorNumber: 'VST-20260803-004',
    date: today,
    timeIn: '10:15',
    timeOut: undefined,
    name: 'Kevin Wijaya',
    category: 'Sales',
    phone: '082144332211',
    email: 'kevin@penerbit-erlangga.co.id',
    destinationUnit: 'Litbang',
    hostPerson: 'Dr. Faisal',
    purpose: 'Presentasi Buku Pembelajaran Kurikulum Merdeka',
    photoUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    visitorCardNumber: 'CARD-008',
    receiverSecurity: 'Moch Saepurrohman',
    status: 'Masih di Sekolah',
    durationMinutes: 100,
    isOverdueAlert: false,
  },
];

export const initialDailyReports: DailyReport[] = [
  {
    id: 'DLY-20260803-01',
    timestamp: `${today} 15:00`,
    date: today,
    shift: 'Siang',
    officers: ['Ismail', 'Ahmad Soleh', 'Andreas Maulana', 'Moch Saepurrohman', 'Rizki Ramadhan'],
    weather: 'Cerah',
    generalSituation: 'Aktivitas KBM berjalan aman dan lancar. Lalu lintas gerbang depan tertib.',
    checklist: {
      gerbang: true,
      gedung: true,
      cctv: true,
      pagar: true,
      lampu: true,
      apar: true,
      parkir: true,
      posSecurity: true,
    },
    notes: 'Kamera CCTV 04 Gedung SD telah dikalibrasi. Seluruh gerbang dikunci tepat pukul 14.30.',
    photos: [
      'https://images.unsplash.com/photo-1582139329536-e7284fece509?w=300&auto=format&fit=crop&q=80',
    ],
    handoverStatus: {
      dayCommander: 'Ismail',
      nightChief: 'Coirul Fikri',
      isSigned: true,
      handoverNotes: 'Kunci master Pos 1 diserahterimakan lengkap beserta 2 unit HT Motorola.',
    },
  },
];

export const initialPatrolLogs: PatrolLog[] = [
  {
    id: 'PTR-101',
    locationId: 'LOC-01',
    locationName: 'Gerbang Utama & Pos 1',
    gedungName: 'Gedung Utama (Direktorat & HRD)',
    timestamp: `${today} 08:00:15`,
    date: today,
    time: '08:00',
    officerName: 'Ismail',
    latitude: -6.3882,
    longitude: 106.8315,
    status: 'Aman',
    notes: 'Pintu gerbang steril, petugas jaga pos lengkap.',
    qrCodeScanned: 'LSMS-PATROL-GERBANG-UTAMA',
  },
  {
    id: 'PTR-102',
    locationId: 'LOC-05',
    locationName: 'Area Playground TK',
    gedungName: 'Gedung TK & PAUD',
    timestamp: `${today} 09:30:22`,
    date: today,
    time: '09:30',
    officerName: 'Andreas Maulana',
    latitude: -6.3885,
    longitude: 106.832,
    status: 'Aman',
    notes: 'Kondisi wahana bermain anak terpantau kokoh dan bersih.',
    qrCodeScanned: 'LSMS-PATROL-TK-PLAYGROUND',
  },
  {
    id: 'PTR-103',
    locationId: 'LOC-04',
    locationName: 'Laboratorium Komputer SMP',
    gedungName: 'Gedung SMP Lazuardi',
    timestamp: `${today} 11:15:00`,
    date: today,
    time: '11:15',
    officerName: 'Ahmad Soleh',
    latitude: -6.3888,
    longitude: 106.8325,
    status: 'Ada Temuan',
    notes: 'Jendela sisi timur tidak terkunci rapat. Sudah dirapatkan.',
    qrCodeScanned: 'LSMS-PATROL-SMP-LAB',
  },
];

export const initialIncidents: IncidentReport[] = [
  {
    id: 'INC-2026-001',
    incidentNumber: 'INC-20260803-01',
    category: 'Kecelakaan',
    location: 'Area Parkir Mobil Gedung GSG',
    date: today,
    time: '11:30',
    officerName: 'Rizki Ramadhan',
    chronology: 'Bumper depan mobil penjemput siswa tergores saat mundur akibat menyenggol tiang pembatas parkir. Tidak ada korban jiwa.',
    photoUrl: 'https://images.unsplash.com/photo-1563720223185-11003d516935?w=300&auto=format&fit=crop&q=80',
    status: 'Closed',
    priority: 'Low',
    actionTaken: 'Membantu pengemudi memeriksa kendaraan dan menyelesaikan pembicaraan secara kekeluargaan.',
  },
  {
    id: 'INC-2026-002',
    incidentNumber: 'INC-20260803-02',
    category: 'Tanpa Izin',
    location: 'Area Belakang Pagar Lapangan SMP',
    date: today,
    time: '13:10',
    officerName: 'Ahmad Soleh',
    chronology: 'Terlihat individu tak dikenal mencoba memanjat pagar perimeter luar dekat lapangan basket.',
    photoUrl: 'https://images.unsplash.com/photo-1541888946425-d0fbb186a5b7?w=300&auto=format&fit=crop&q=80',
    status: 'Open',
    priority: 'Critical',
    actionTaken: 'Petugas patroli menyalakan sirine pos dan mengamankan lokasi. Individu melarikan diri ke luar area.',
  },
];

export const initialLostAndFound: LostAndFound[] = [
  {
    id: 'LNF-001',
    itemName: 'Botol Minum Tupperware Hijau (Ada Stiker Nama Rayhan)',
    dateFound: today,
    location: 'Kantin Sekolah SD',
    foundBy: 'Andyka Jessy Saputra',
    status: 'Belum Diambil',
    photoUrl: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=200&auto=format&fit=crop&q=80',
    notes: 'Disimpan di etalase Pos Security Utama.',
  },
  {
    id: 'LNF-002',
    itemName: 'Jaket Hoodie Hitam Brand Uniqlo Size M',
    dateFound: today,
    location: 'Tribun GSG',
    foundBy: 'Moch Saepurrohman',
    status: 'Sudah Diambil',
    photoUrl: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=200&auto=format&fit=crop&q=80',
    claimedBy: 'Ibu Farida (Orang Tua Siswa)',
    claimedPhone: '081234567890',
    claimDate: `${today} 14:20`,
    notes: 'Pemilik menyerahkan bukti foto anaknya memakai hoodie tersebut.',
  },
];

export const initialBarangTitipan: BarangTitipan[] = [
  {
    id: 'TTP-001',
    ownerName: 'Ibu Hendriati (Ortu Ananda Sarah 5 SD)',
    phone: '081298877665',
    itemDescription: 'Kotak Makanan Siang + Obat Penurun Panas',
    timeIn: '10:00',
    dateIn: today,
    receiverSecurity: 'Ismail',
    status: 'Sudah Diambil',
    timeOut: '12:15',
    dateOut: today,
    digitalSignature: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="100" height="40"><path d="M10 20 Q 30 5, 50 20 T 90 20" stroke="black" fill="none"/></svg>',
  },
  {
    id: 'TTP-002',
    ownerName: 'Pak Dedi (Pengantar Paket J&T)',
    phone: '081377665544',
    itemDescription: 'Dokumen Amplop Coklat Paket Litbang (Untuk Dr. Faisal)',
    timeIn: '11:40',
    dateIn: today,
    receiverSecurity: 'Ahmad Soleh',
    status: 'Dititipkan',
  },
];

export const initialVehiclesLog: SchoolVehicleLog[] = [
  {
    id: 'VLOG-001',
    vehicleName: 'Daihatsu Gran Max Box',
    plateNumber: 'B 1840 LZ',
    driverName: 'Pak Herman',
    destination: 'Dinas Pendidikan Depok & Toko Sarpras',
    dateOut: today,
    timeOut: '09:00',
    status: 'Masih Keluar',
    purpose: 'Pengambilan seragam sekolah & pengantaran berkas dinas.',
  },
  {
    id: 'VLOG-002',
    vehicleName: 'Toyota HiAce Silver',
    plateNumber: 'B 1029 LZ',
    driverName: 'Pak Yudi',
    destination: 'Museum Nasional Jakarta',
    dateOut: today,
    timeOut: '07:30',
    timeIn: '14:00',
    status: 'Sudah Kembali',
    purpose: 'Outing Class Murid Kelas 8 SMP Lazuardi.',
  },
];

export const initialNotifications: SystemNotification[] = [
  {
    id: 'NOTIF-01',
    type: 'visitor_overdue',
    title: 'Peringatan Visitor Terlama (>4 Jam)',
    message: 'Visitor Bambang Triyono (CARD-012, AC Service) belum checkout sejak 07:15 (Durasi > 5 Jam). Mohon konfirmasi lokasi!',
    timestamp: `${today} 12:15`,
    read: false,
    linkModule: 'visitor-checkout',
  },
  {
    id: 'NOTIF-02',
    type: 'incident_critical',
    title: 'Insiden Tingkat CRITICAL Terdeteksi',
    message: 'Insiden INC-20260803-02 (Coba Masuk Tanpa Izin di Pagar SMP) membutuhkan perhatian cepat dari Supervisor.',
    timestamp: `${today} 13:12`,
    read: false,
    linkModule: 'incidents',
  },
];

export const initialAuditLogs: AuditLog[] = [
  {
    id: 'AUD-001',
    timestamp: `${today} 07:15:10`,
    userName: 'Ismail',
    userRole: 'User',
    action: 'CHECK_IN_VISITOR',
    module: 'Visitor Management',
    details: 'Check in Visitor Bambang Triyono (CARD-012, Vendor AC)',
  },
  {
    id: 'AUD-002',
    timestamp: `${today} 08:00:15`,
    userName: 'Ismail',
    userRole: 'User',
    action: 'SCAN_PATROL_QR',
    module: 'Patroli Security',
    details: 'Scan titik QR Gerbang Utama (LSMS-PATROL-GERBANG-UTAMA) - Status Aman',
  },
  {
    id: 'AUD-003',
    timestamp: `${today} 13:10:00`,
    userName: 'Ahmad Soleh',
    userRole: 'Administrator',
    action: 'CREATE_INCIDENT_REPORT',
    module: 'Laporan Insiden',
    details: 'Membuat laporan insiden CRITICAL: Coba masuk tanpa izin di area Pagar SMP',
  },
];
